# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_game.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(594, 473)
        Dialog.setMinimumSize(QtCore.QSize(594, 452))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 88989))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/иконка2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-image: url(Images/1.jpg);")
        self.close_btn = QtWidgets.QPushButton(Dialog)
        self.close_btn.setGeometry(QtCore.QRect(420, 400, 151, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.close_btn.setFont(font)
        self.close_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_btn.setStyleSheet("color: rgb(180, 180, 180);")
        self.close_btn.setObjectName("close_btn")
        self.info = QtWidgets.QPlainTextEdit(Dialog)
        self.info.setEnabled(False)
        self.info.setGeometry(QtCore.QRect(20, 20, 551, 361))
        self.info.setMinimumSize(QtCore.QSize(491, 341))
        self.info.setMaximumSize(QtCore.QSize(897, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.info.setFont(font)
        self.info.setStyleSheet("color: rgb(180, 180, 180);")
        self.info.setObjectName("info")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Об игре"))
        self.close_btn.setText(_translate("Dialog", "Закрыть"))
        self.close_btn.setShortcut(_translate("Dialog", "Return"))
        self.info.setPlainText(_translate("Dialog", "Космос скрывает множество тайн и загадок...Однажды весьма загадочным образом образовался некий разрыв пространства, кротовая нора, ведущая за сотни миллионов километров от родной галактики. \n"
"Вы станете первооткрывателем, но помните, время — величина весьма непостоянная, а также очень ценный ресурс. Берегите его и принимайте решения с умом, пусть на этот раз вселенная станет чуточку яснее..."))
