# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'account_of_travel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(543, 800)
        Form.setMinimumSize(QtCore.QSize(543, 800))
        Form.setMaximumSize(QtCore.QSize(543, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/иконка2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-image: url(:/newPrefix/бумага.jpg);")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, -10, 541, 811))
        self.widget.setStyleSheet("background-image: url(Images/бумага.jpg);")
        self.widget.setObjectName("widget")
        self.textEdit = QtWidgets.QTextBrowser(self.widget)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 521, 761))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("color: rgb(200, 200, 200);\n"
"background-image: url(Images/бумага.jpg);")
        self.textEdit.setObjectName("textEdit")
        self.closeb = QtWidgets.QPushButton(self.widget)
        self.closeb.setGeometry(QtCore.QRect(200, 750, 131, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.closeb.setFont(font)
        self.closeb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeb.setStyleSheet("color: rgb(198, 198, 198);")
        self.closeb.setObjectName("closeb")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Отчет о путешествии"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Sans Serif\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.closeb.setText(_translate("Form", "Закрыть"))
        self.closeb.setShortcut(_translate("Form", "Return"))
