# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'birthday_date.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 472)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/иконка2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-image: url(Images/1.jpg);")
        Dialog.setModal(True)
        self.calendarWidget = QtWidgets.QCalendarWidget(Dialog)
        self.calendarWidget.setGeometry(QtCore.QRect(20, 10, 411, 401))
        self.calendarWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calendarWidget.setStyleSheet("color: rgb(206, 206, 206);\n"
"alternate-background-color: rgb(16, 17, 34);\n"
"border-image: url(Images/1.jpg);\n"
"background-image: url(Images/1.jpg);")
        self.calendarWidget.setObjectName("calendarWidget")
        self.choose = QtWidgets.QPushButton(Dialog)
        self.choose.setGeometry(QtCore.QRect(190, 420, 101, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.choose.setFont(font)
        self.choose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.choose.setStyleSheet("color: rgb(190, 190, 190);")
        self.choose.setObjectName("choose")
        self.cansel = QtWidgets.QPushButton(Dialog)
        self.cansel.setGeometry(QtCore.QRect(330, 420, 101, 41))
        self.cansel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.cansel.setFont(font)
        self.cansel.setStyleSheet("color: rgb(189, 189, 189);")
        self.cansel.setObjectName("cansel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Выберите дату"))
        self.choose.setText(_translate("Dialog", "Выбрать"))
        self.choose.setShortcut(_translate("Dialog", "Return"))
        self.cansel.setText(_translate("Dialog", "Отмена"))
