# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_guide.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(570, 384)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/иконка2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-image: url(Images/1.jpg);")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 571, 391))
        self.widget.setStyleSheet("background-image: url(Images/1.jpg);")
        self.widget.setObjectName("widget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget)
        self.plainTextEdit.setEnabled(False)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 20, 511, 301))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("color: rgb(190, 190, 190);\n"
"background-image: url(Images/1.jpg);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.ok = QtWidgets.QPushButton(self.widget)
        self.ok.setGeometry(QtCore.QRect(230, 330, 111, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.ok.setFont(font)
        self.ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok.setStyleSheet("color: rgb(190, 190, 190);")
        self.ok.setObjectName("ok")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Руководство к игре"))
        self.plainTextEdit.setPlainText(_translate("Form", "\n"
"Выбирайте варианты ответов. Все они влияют на сюжет и приводят к одной из четырех концовок. \n"
"Можно сохранить игру, нажав  \"Выйти из игры\", затем \"Сохранить\". Далее при нажатии на кнопку  \"Продолжить\" в Главном меню можно вернуться к сохраненной игре.\n"
""))
        self.ok.setText(_translate("Form", "Ясно"))
        self.ok.setShortcut(_translate("Form", "Return"))
