# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info_about_ends.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(569, 354)
        Form.setMinimumSize(QtCore.QSize(569, 354))
        Form.setMaximumSize(QtCore.QSize(569, 354))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/иконка2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 571, 671))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-image: url(Images/фон концовки.jpg);\n"
"color: rgb(194, 194, 194);")
        self.textEdit.setObjectName("textEdit")
        self.go_to_end = QtWidgets.QPushButton(Form)
        self.go_to_end.setEnabled(True)
        self.go_to_end.setGeometry(QtCore.QRect(70, 280, 241, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.go_to_end.setFont(font)
        self.go_to_end.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.go_to_end.setStyleSheet("color: rgb(200, 200, 200);\n"
"background-image: url(Images/фон концовки.jpg);")
        self.go_to_end.setObjectName("go_to_end")
        self.close_ = QtWidgets.QPushButton(Form)
        self.close_.setEnabled(True)
        self.close_.setGeometry(QtCore.QRect(360, 280, 141, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.close_.setFont(font)
        self.close_.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_.setStyleSheet("background-image: url(Images/небо.jpg);\n"
"color: rgb(200, 200, 200);")
        self.close_.setObjectName("close_")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Описание"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Sans Serif\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Потеряли все.</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Порой люди берут на себя слишком много.. Вы надеялись на удачу, а в итоге не спасли напарника и не спаслись сами, потеряли все свои исследования. Хорошо, что это всего-лишь игра, которую всегда можно перепройти заново.</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.go_to_end.setText(_translate("Form", "Перейти к концовке"))
        self.close_.setText(_translate("Form", "Закрыть"))
