# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'item_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(341, 195)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/иконка2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-image: url(Images/1.jpg);")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 341, 211))
        self.widget.setStyleSheet("background-image: url(Images/1.jpg);")
        self.widget.setObjectName("widget")
        self.name = QtWidgets.QLabel(self.widget)
        self.name.setGeometry(QtCore.QRect(10, 10, 321, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.name.setFont(font)
        self.name.setStyleSheet("color: rgb(198, 198, 198);")
        self.name.setText("")
        self.name.setObjectName("name")
        self.delete_2 = QtWidgets.QPushButton(self.widget)
        self.delete_2.setGeometry(QtCore.QRect(20, 130, 301, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.delete_2.setFont(font)
        self.delete_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_2.setStyleSheet("color: rgb(188, 39, 34);")
        self.delete_2.setObjectName("delete_2")
        self.use = QtWidgets.QPushButton(self.widget)
        self.use.setEnabled(False)
        self.use.setGeometry(QtCore.QRect(20, 70, 301, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.use.setFont(font)
        self.use.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.use.setStyleSheet("color: rgb(190, 190, 190);")
        self.use.setObjectName("use")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Вещь"))
        self.delete_2.setText(_translate("Form", "Убрать"))
        self.use.setText(_translate("Form", "Использовать"))
