# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_inventary.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(618, 280)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/иконка2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-image: url(Images/1.jpg);")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 621, 281))
        self.widget.setStyleSheet("background-image: url(Images/1.jpg);")
        self.widget.setObjectName("widget")
        self.invent_list = QtWidgets.QListWidget(self.widget)
        self.invent_list.setGeometry(QtCore.QRect(20, 40, 591, 211))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.invent_list.setFont(font)
        self.invent_list.setStyleSheet("background-image: url(Images/1.jpg);\n"
"color: rgb(200, 200, 200);")
        self.invent_list.setObjectName("invent_list")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(240, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(198, 198, 198);")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Инвентарь"))
        self.label_3.setText(_translate("Form", "Инвентарь"))
